version: '3'

services:

    php:
        container_name: php
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - appdata:/var/www
            #- ./magento24/app:/var/www/magento24/app:delegated
            #- ./magento24/composer.json:/var/www/magento24/composer.json:delegated
            #- ./magento24/composer.lock:/var/www/magento24/composer.lock:delegated
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            PHP_XDEBUG_ENABLED: 1
            XDEBUG_CONFIG: remote_host=host.docker.internal
            PHP_IDE_CONFIG: "serverName=magento24"
 
    nginx:
        container_name: nginx
        image: nginx:1.14-alpine
        ports:
            - 80:80
        volumes:
            - ./magento24:/var/www/magento24:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/m2-config/nginx.conf:/var/www/nginx.conf
        depends_on:
            - php
 
    db:
        container_name: mariadb
        image: mariadb:10.4
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    mailhog:
        container_name: mail
        image: mailhog/mailhog:latest
        links:
            - php
        ports:
            - "1025:1025"
            - "8025:8025"
            
    redis:
        container_name: redis
        image: redis:latest
        
    redisinsight:
      container_name: redisinsight
      image: redislabs/redisinsight:latest
      ports:
          - 8001:8001

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"

    elasticsearch:
        image: elasticsearch:7.6.2
        container_name: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            "discovery.type": "single-node"
     
     kibana:
        image: kibana:7.6.2
        container_name: kibana-m243
        ports:
            - "5601:5601"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin-m243
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: "mariadb-m243"
            PMA_PORT: "3306"
            PMA_USER: "root" 
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    #blackfire:
    #    container_name: blackfire
    #    image: blackfire/blackfire
    #    ports: ["8707"]
    #    environment:
    #        # Exposes BLACKFIRE_* environment variables from the host
    #        BLACKFIRE_SERVER_ID: ### Add server id ####
    #        BLACKFIRE_SERVER_TOKEN: ### Add server token ###
    #        BLACKFIRE_CLIENT_ID: ### Add client id ###
    #        BLACKFIRE_CLIENT_TOKEN: ### Add client Token ###

volumes:
    appdata:
